spring:
  redis:
    host: 192.168.153.130
  datasource:
    url: jdbc:mysql://localhost:3306/config-db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
server:
  port: 8001
mybatis:
  mapper-locations: classpath*:mapper/*.xml